### ISSUE TITLE
Class 'TeamSpeak3_Helper_String' not found

### ISSUE THREAD

**Issue by RikoDEV** [planetteamspeak/ts3phpframework#137]
When I want to connect to the Team Speak server I get the error:

```
Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'TeamSpeak3_Helper_String' not found

at /var/www/domain.com/vendor/planetteamspeak/ts3-php-framework/libraries/TeamSpeak3/Helper/Uri.php:218
    214|    * @return TeamSpeak3_Helper_String
    215|    */
    216|   public function getScheme($default = null)
    217|   {
  > 218|     return ($this->hasScheme()) ? new TeamSpeak3_Helper_String($this->scheme) : $default;
    219|   }
    220|
    221|   /**
    222|    * Returns TRUE if the username is valid.
```

PHP 7.4.2
Laravel 6.8.0

My code:

```
use TeamSpeak3;
use TeamSpeak3_Exception;

try {

    $ts3_VirtualServer = TeamSpeak3::factory("serverquery://x.x.x.x:10011/?server_port=9987");

    $name = $ts3_VirtualServer->clientGetById(47);
    print_r($name->getInfo(TRUE));

} catch(TeamSpeak3_Exception $e) {

    return "Error " . $e->getCode() . ": " . $e->getMessage();

}
```

**Comment by svenpaulsen** [comment]
Seems to be an autoloading issue. I'll take a look at this as soon as I get the chance, but for now, I'd suggest including the `TeamSpeak3/Helper/String.php` file (and others you might need) manually.

**Comment by Sebi94nbg** [comment]
I have the same problem.

Seems like as it's related to PHP 7.4, because with PHP 7.3 I don't had this issue.

I've also tested older versions of this library, but downgrading didn't fix this issue.

**Comment by SebastianKramerVATGer** [comment]
Had the same problems upgrading to PHP7.4.

Found out that it is related to this deprecation:
https://wiki.php.net/rfc/deprecate_curly_braces_array_access.

Fixing the Helper/String.php and also the Adapter/Host.php

It is working fine for me again.

**Comment by ronindesign** [comment]
Master has a merged PR regarding replacing curly braces with brackets. Maybe it is related and would resolve this? #142

**Comment by Sebi94nbg** [comment]
I've checked out the current master (`dev-master b14b8c8`), but I'm still getting the same error message as reported in the first comment.

So no, this does not resolve it.

**Comment by Sebi94nbg** [comment]
I've created a PR #145. As soon as this is merged, I'll test this issue again with the current code from the `develop` branch.

**Comment by Sebi94nbg** [comment]
Any news regarding this issue?

**Comment by ronindesign** [comment]
I commented on your PR, was waiting for you to resolve the Travis CI ssh issue before merging into `dev`.

**Comment by Sebi94nbg** [comment]
I've unfortunately not found any solution to install the PHP extension `ssh2`. All what I've found with Google didn't work. :(

**Comment by ronindesign** [comment]
It might be a bit overkill, but maybe we could compile the extension from source for each instance...?

**Comment by Sebi94nbg** [comment]
Some changes and fixes have been merged into `dev`. Let's test and fix this issue on this branch.

**Comment by Sebi94nbg** [comment]
Ok, just tested the `dev` branch. It fixed the initial issue. I just got the error `Class 'TeamSpeak3' not found` after "updating" the library, but this was easily fixed by reimporting the classes with the new namespace.

Old:
`use TeamSpeak3;`

New:
`use PlanetTeamSpeak\TeamSpeak3Framework\TeamSpeak3;`

After changing this, I get now the following error message:

```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method PlanetTeamSpeak\TeamSpeak3Framework\TeamSpeak3::getAdapterName()

  at /home/vagrant/vendor/planetteamspeak/ts3-php-framework/src/TeamSpeak3.php:337
    333|         self::init();
    334| 
    335|         $uri = new Uri($uri);
    336| 
  > 337|         $adapter = self::getAdapterName($uri->getScheme());
    338|         $options = ["host" => $uri->getHost(), "port" => $uri->getPort(), "timeout" => (int) $uri->getQueryVar("timeout", 10), "blocking" => (int) $uri->getQueryVar("blocking", 1), "tls" => (int) $uri->getQueryVar("tls", 0), "ssh" => (int) $uri->getQueryVar("ssh", 0)];
    339| 
    340|         self::loadClass($adapter);
    341| 
```

**Comment by Sebi94nbg** [comment]
I've fixed that issue, but there is now a different issue.
```
   ErrorException  : scandir(TeamSpeak3/Adapter/): failed to open dir: No such file or directory

  at /home/vagrant/vendor/planetteamspeak/ts3-php-framework/src/TeamSpeak3.php:416
    412| 
    413|   protected static function getAdapterName($name, $namespace = "TeamSpeak3_Adapter_")
    414|              {
    415|                              $path = self::getFilePath($namespace);
  > 416|                                      $scan = scandir($path);
        }
    417| 
    418|                                      foreach($scan as $node)
    419|                                                      {
    420|                                                                          $file = StringHelper::factory($node)->toLower();
```

Running from one issue to another one. :(

Could someone of you take a look at this please? @ronindesign @svenpaulsen

**Comment by Sebi94nbg** [comment]
Any news?

**Comment by Sebi94nbg** [comment]
Any updates?

**Comment by ronindesign** [comment]
@Sebi94nbg Apologies this has been blocking you. I've not had much time to work on this recently.

Looking back at the error, two thoughts I have:
1) Does this directory actually exist?
`/home/vagrant/vendor/planetteamspeak/ts3-php-framework/src/TeamSpeak3/Adapter/`

2) Is the `scandir($path)` relative? I.e. if you're running framework from something like `/home/vagrant`, it might be trying to find `/home/vagrant/TeamSpeak3/Adapter/` and erroring out?

Though, I would think autoloader would manage this and `scandir()` call would be relative to `TeamSpeak3.php`'s location, so I'm back to square one... not sure why it's not finding the relative directory path.

Maybe you can troubleshoot by doing `getcwd()` something like:
```php
 protected static function getAdapterName($name, $namespace = "TeamSpeak3_Adapter_")
              {
                             $path = self::getFilePath($namespace);
                                     var_dump(getcwd()); // or even die(getcwd());
                                     $scan = scandir($path);
                                     ...
```

Just to confirm the relative path? Apologies, again I don't have much time to test if composer / autoloading issue.

**Comment by Katalam** [comment]
I still get the same issue as described in the very first comment. Is there any fix for this?

Class "TeamSpeak3_Node_Server" not found
C:\Users\admin\Documents\UCP\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Host.php:286

It works locally on mac os but windows.

**Comment by jballzz** [comment]
I am also having this issue, mine started causing an error when i updated composer to version 2 ?

**Comment by Domenikus** [comment]
Same for me

**Comment by CommandCrafterHD** [comment]
I'll just chime in and share how I fixed the "TeamSpeak3_Node_Server" issue (at least locally, some other issues might still arise with these fixes)
I inserted a simple require at the top of "Adapter\ServerQuery.php"
`require('S:\wwwroot\website\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Host.php');`
(Your path may vary)
I also inserted a require into "Node\Host.php"
`require('S:\wwwroot\website\vendor\planetteamspeak\ts3-php-framework\libraries\TeamSpeak3\Node\Server.php');`
And at last I changed `$id1` into `$id1 = 0` in lines 2021 and 2036 within Node\Server.php

I hope I can help someone with this ^^

**Comment by dannyot** [comment]
Hey there?  a new Solution? 

I did  a workarround just implement it without composer. So download and Copy. This works fine. However, not the best solution.

**Comment by ronindesign** [comment]
Closing this for now as I believe it is resolved in dev branch. Please target that in composer unless you experience issues.
